const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={currentFile:null,currentImg:null,outputUrl:null,originalUrl:null,tool:null,category:"all",query:""};

const tools=[
["compress","images","🗜️","Image Compressor","Reduce JPG, PNG or WebP file size in your browser.","Popular"],
["resize","images","↔️","Image Resizer","Change image dimensions while keeping proportions when needed.","Popular"],
["convert","images","🔄","Image Converter","Convert JPG, PNG and WebP formats.","Popular"],
["crop","images","✂️","Image Cropper","Crop an image to a custom rectangle and download it.","New"],
["rotate","images","⟳","Image Rotator","Rotate an image 90°, 180° or 270°.","New"],
["words","text","Aa","Word Counter","Count words, characters, lines and estimated reading time.","Popular"],
["case","text","Aa","Case Converter","Convert text to upper, lower, title or sentence case.",""],
["dedupe","text","≡","Duplicate Line Remover","Remove repeated lines while preserving order.",""],
["slug","text","⌁","Slug Generator","Turn a title into a clean URL-friendly slug.",""],
["sortlines","text","↕","Line Sorter","Sort lines alphabetically or numerically.",""],
["percent","calculators","%","Percentage Calculator","Calculate a percentage of a number.","Popular"],
["discount","calculators","−%","Discount Calculator","Calculate discount amount and final price.","New"],
["tip","calculators","☕","Tip Calculator","Split a bill and calculate a tip per person.",""],
["age","calculators","🎂","Age Calculator","Calculate age from a date of birth.",""],
["average","calculators","∑","Average Calculator","Calculate the mean of a list of numbers.",""],
["length","converters","↔","Length Converter","Convert common length units.","Popular"],
["weight","converters","⚖","Weight Converter","Convert common weight and mass units.",""],
["temperature","converters","°","Temperature Converter","Convert Celsius, Fahrenheit and Kelvin.",""],
["data","converters","▣","Data Size Converter","Convert bytes, KB, MB, GB and TB.",""],
["timezones","converters","◷","Minutes Converter","Convert seconds, minutes, hours and days.",""],
["password","generators","🔐","Password Generator","Create a random password locally in your browser.","Popular"],
["uuid","generators","#","UUID Generator","Generate UUID v4 values locally.","New"],
["random","generators","⚄","Random Number Generator","Generate random numbers within a range.",""],
["lorem","generators","¶","Lorem Ipsum Generator","Generate placeholder text for layouts and prototypes.",""],
["base64","developer","<>","Base64 Encoder / Decoder","Encode or decode Base64 text in your browser.",""],
["url","developer","🔗","URL Encoder / Decoder","Encode or decode URL components.",""],
["json","developer","{ }","JSON Formatter","Format, validate and minify JSON.","Popular"],
["sha","developer","#","SHA-256 Hash","Create a SHA-256 hash using the Web Crypto API.",""],
["timestamp","time","◷","Unix Timestamp","Convert between dates and Unix timestamps.","New"],
["countdown","time","⏱","Countdown Timer","Run a simple countdown timer in the browser.",""]
];

const descriptions=Object.fromEntries(tools.map(t=>[t[0],[t[3],t[4]]]));
const grid=$("#toolGrid"), search=$("#toolSearch"), heroSearch=$("#heroSearch");

function renderTools(){
  const q=state.query.toLowerCase().trim();
  const list=tools.filter(t=>(state.category==="all"||t[1]===state.category)&&(!q||(t[3]+" "+t[4]+" "+t[1]).toLowerCase().includes(q)));
  grid.innerHTML=list.map(t=>`<button class="tool-card" data-tool="${t[0]}"><div class="tool-icon">${t[2]}</div><h3>${t[3]}</h3><p>${t[4]}</p><div class="tool-meta">${t[5]?`<span>${t[5]}</span>`:""}<span>${t[1]}</span></div></button>`).join("");
  $("#emptyTools").classList.toggle("hidden",list.length>0);
  $$(".tool-card").forEach(b=>b.onclick=()=>showTool(b.dataset.tool));
}
renderTools();

$$(".cat").forEach(b=>b.onclick=()=>{$$(".cat").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.category=b.dataset.cat;renderTools()});
search.oninput=e=>{state.query=e.target.value;renderTools()};
heroSearch.oninput=e=>{search.value=e.target.value;state.query=e.target.value;location.hash="tools";renderTools()};
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();heroSearch.focus()}});

$("#themeToggle").onclick=()=>{document.body.classList.toggle("dark");$("#themeToggle").textContent=document.body.classList.contains("dark")?"☀":"☾";localStorage.setItem("utilora-theme",document.body.classList.contains("dark")?"dark":"light")};
if(localStorage.getItem("utilora-theme")==="dark"){document.body.classList.add("dark");$("#themeToggle").textContent="☀"}

const workspace=$("#workspace"), content=$("#toolContent"), title=$("#toolTitle"), desc=$("#toolDescription");
$("#back").onclick=()=>{workspace.classList.add("hidden");location.hash="tools";window.scrollTo({top:document.querySelector("#tools").offsetTop-70,behavior:"smooth"})};

function showTool(t){
  const d=descriptions[t]||["Tool","Utility"];
  state.tool=t;title.textContent=d[0];desc.textContent=d[1];workspace.classList.remove("hidden");location.hash="workspace";
  content.innerHTML=""; const fn=toolFns[t]; if(fn) fn(); addGuide(t);
  setTimeout(()=>workspace.scrollIntoView({behavior:"smooth",block:"start"}),30);
}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function bytes(n){if(!n)return"0 B";const u=["B","KB","MB","GB"];const i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function fileInput(){return`<label class="drop"><input id="toolFile" type="file" accept="image/jpeg,image/png,image/webp"><div><b>Click to choose an image</b><p class="muted">JPG, PNG or WebP · max 20 MB</p></div></label>`}
function loadImage(file,after){if(!file)return;if(file.size>20*1024*1024)return alert("Maximum file size is 20 MB.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))return alert("Please choose JPG, PNG or WebP.");state.currentFile=file;if(state.originalUrl)URL.revokeObjectURL(state.originalUrl);state.originalUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{state.currentImg=img;after(img)};img.src=state.originalUrl}
function renderImageTool(type){
  let extra=type==="compress"?`<div class="field"><label>Quality: <span id="qv">75%</span></label><input id="quality" class="range" type="range" min="10" max="100" value="75"></div>`:
  type==="resize"?`<div class="row"><div class="field"><label>Width (px)</label><input id="w" class="input" type="number" min="1"></div><div class="field"><label>Height (px)</label><input id="h" class="input" type="number" min="1"></div></div><label class="check"><input id="lock" type="checkbox" checked> Keep aspect ratio</label>`:
  `<div class="field"><label>Output format</label><select id="format" class="input"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></div>`;
  content.innerHTML=`<div class="tool-ui">${fileInput()}${extra}<div id="previewArea"></div><div id="result"></div></div>`;
  $("#toolFile").onchange=e=>loadImage(e.target.files[0],img=>{if($("#w")){$("#w").value=img.width;$("#h").value=img.height}processImage(type)});
  if($("#quality"))$("#quality").oninput=e=>{$("#qv").textContent=e.target.value+"%";if(state.currentImg)processImage(type)};
  if($("#w")){$("#w").oninput=()=>processImage(type);$("#h").oninput=()=>processImage(type)}
  if($("#format"))$("#format").onchange=()=>processImage(type);
  if($("#lock"))$("#w").oninput=e=>{if($("#lock").checked&&state.currentImg){const r=state.currentImg.height/state.currentImg.width;$("#h").value=Math.round(Number(e.target.value)*r)}processImage(type)};
}
function processImage(type){
  const img=state.currentImg;if(!img)return;let w=img.width,h=img.height;
  if(type==="resize"){w=Math.max(1,parseInt($("#w").value)||img.width);h=Math.max(1,parseInt($("#h").value)||img.height)}
  else{const s=Math.min(1,2600/Math.max(w,h));w=Math.round(w*s);h=Math.round(h*s)}
  const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);
  const mime=type==="convert"?$("#format").value:"image/jpeg",q=type==="compress"?Number($("#quality").value)/100:.9;
  if(type==="resize"&&state.currentFile.type==="image/png")mime="image/png";
  c.toBlob(blob=>{if(!blob)return;state.outputUrl&&URL.revokeObjectURL(state.outputUrl);state.outputUrl=URL.createObjectURL(blob);$("#previewArea").innerHTML=`<img class="preview" src="${state.outputUrl}" alt="Processed preview">`;const saved=state.currentFile?Math.round((1-blob.size/state.currentFile.size)*100):0;$("#result").innerHTML=`<div class="output"><b>${bytes(blob.size)}</b> output · ${saved>=0?saved:0}% smaller<div class="actions"><button class="btn" id="dl">Download result</button></div></div>`;$("#dl").onclick=()=>downloadBlob(blob,state.currentFile.name.replace(/\.[^.]+$/,"")+"-utilora."+mime.split("/")[1].replace("jpeg","jpg"))},mime,q);
}
const imageFns={compress:()=>renderImageTool("compress"),resize:()=>renderImageTool("resize"),convert:()=>renderImageTool("convert")};
function cropTool(){content.innerHTML=`<div class="tool-ui">${fileInput()}<div class="row"><div class="field"><label>Crop X</label><input id="cx" class="input" type="number" value="0"></div><div class="field"><label>Crop Y</label><input id="cy" class="input" type="number" value="0"></div></div><div class="row"><div class="field"><label>Width</label><input id="cw" class="input" type="number"></div><div class="field"><label>Height</label><input id="ch" class="input" type="number"></div></div><button class="btn" id="cropGo">Crop & download</button><div id="cropPreview"></div></div>`;$("#toolFile").onchange=e=>loadImage(e.target.files[0],img=>{$("#cw").value=img.width;$("#ch").value=img.height;$("#cropPreview").innerHTML=`<img class="preview" src="${state.originalUrl}" alt="Original preview">`});$("#cropGo").onclick=()=>{const i=state.currentImg;if(!i)return alert("Choose an image first.");const x=Math.max(0,Number($("#cx").value)||0),y=Math.max(0,Number($("#cy").value)||0),w=Math.min(i.width-x,Number($("#cw").value)||i.width),h=Math.min(i.height-y,Number($("#ch").value)||i.height);if(w<=0||h<=0)return alert("Crop area is outside the image.");const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(i,x,y,w,h,0,0,w,h);c.toBlob(b=>downloadBlob(b,state.currentFile.name.replace(/\.[^.]+$/,"")+"-cropped.png"),"image/png")}}
function rotateTool(){content.innerHTML=`<div class="tool-ui">${fileInput()}<div class="field"><label>Rotation</label><select id="deg" class="input"><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div><button class="btn" id="rotGo">Rotate & download</button><div id="rotPreview"></div></div>`;$("#toolFile").onchange=e=>loadImage(e.target.files[0],()=>$("#rotPreview").innerHTML=`<img class="preview" src="${state.originalUrl}" alt="Original preview">`);$("#rotGo").onclick=()=>{const i=state.currentImg;if(!i)return alert("Choose an image first.");const d=Number($("#deg").value),r=d*Math.PI/180,c=document.createElement("canvas");c.width=d===180?i.width:i.height;c.height=d===180?i.height:i.width;const x=c.getContext("2d");x.translate(c.width/2,c.height/2);x.rotate(r);x.drawImage(i,-i.width/2,-i.height/2);c.toBlob(b=>downloadBlob(b,state.currentFile.name.replace(/\.[^.]+$/,"")+"-rotated.png"),"image/png")}}

function wordTool(){content.innerHTML=`<div class="tool-ui"><textarea id="text" class="input" rows="13" placeholder="Paste or type your text here..."></textarea><div class="three"><div class="output"><span>Words</span><div id="wc" class="big">0</div></div><div class="output"><span>Characters</span><div id="cc" class="big">0</div></div><div class="output"><span>Lines</span><div id="lc" class="big">0</div></div></div><div class="output"><span>Estimated reading time</span><div id="rt" class="big">0 min</div></div></div>`;$("#text").oninput=e=>{const t=e.target.value,w=t.trim()?t.trim().split(/\s+/).length:0;$("#wc").textContent=w;$("#cc").textContent=t.length;$("#lc").textContent=t?t.split(/\r?\n/).length:0;$("#rt").textContent=w?Math.max(1,Math.ceil(w/200))+" min":"0 min"}}
function caseTool(){content.innerHTML=`<div class="tool-ui"><textarea id="caseIn" class="input" rows="10" placeholder="Enter text..."></textarea><div class="actions"><button class="btn" data-case="upper">UPPERCASE</button><button class="btn" data-case="lower">lowercase</button><button class="btn" data-case="title">Title Case</button><button class="btn" data-case="sentence">Sentence case</button></div><textarea id="caseOut" class="input" rows="10" readonly placeholder="Result..."></textarea></div>`;$$("[data-case]").forEach(b=>b.onclick=()=>{const t=$("#caseIn").value,mode=b.dataset.case;let o=t;if(mode==="upper")o=t.toUpperCase();if(mode==="lower")o=t.toLowerCase();if(mode==="title")o=t.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());if(mode==="sentence")o=t.toLowerCase().replace(/(^\s*\w|[.!?]\s+\w)/g,c=>c.toUpperCase());$("#caseOut").value=o})}
function dedupeTool(){content.innerHTML=`<div class="tool-ui"><textarea id="dupIn" class="input" rows="12" placeholder="One line per item..."></textarea><button class="btn" id="dedupeGo">Remove duplicates</button><textarea id="dupOut" class="input" rows="12" readonly placeholder="Unique lines..."></textarea></div>`;$("#dedupeGo").onclick=()=>{$("#dupOut").value=[...new Set($("#dupIn").value.split(/\r?\n/))].join("\n")}}
function slugTool(){content.innerHTML=`<div class="tool-ui"><input id="slugIn" class="input" placeholder="Your page title"><div class="output"><div id="slugOut" class="big">your-slug</div></div><button class="btn" id="slugCopy">Copy slug</button></div>`;$("#slugIn").oninput=e=>$("#slugOut").textContent=e.target.value.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"your-slug";$("#slugCopy").onclick=()=>navigator.clipboard?.writeText($("#slugOut").textContent)}
function sortTool(){content.innerHTML=`<div class="tool-ui"><textarea id="sortIn" class="input" rows="12" placeholder="One line per item..."></textarea><select id="sortMode" class="input"><option value="az">A → Z</option><option value="za">Z → A</option><option value="num">Numeric</option></select><button class="btn" id="sortGo">Sort lines</button><textarea id="sortOut" class="input" rows="12" readonly></textarea></div>`;$("#sortGo").onclick=()=>{let a=$("#sortIn").value.split(/\r?\n/);if($("#sortMode").value==="az")a.sort((x,y)=>x.localeCompare(y));if($("#sortMode").value==="za")a.sort((x,y)=>y.localeCompare(x));if($("#sortMode").value==="num")a.sort((x,y)=>(parseFloat(x)||0)-(parseFloat(y)||0));$("#sortOut").value=a.join("\n")}}

function simpleCalc(titleText,html,calc){content.innerHTML=`<div class="tool-ui">${html}<button class="btn" id="calcGo">Calculate</button><div id="calcOut" class="output hidden"></div></div>`;$("#calcGo").onclick=()=>{const v=calc();$("#calcOut").classList.remove("hidden");$("#calcOut").innerHTML=`<div class="big">${esc(v)}</div>`}}
function percentTool(){simpleCalc("Percentage",`<div class="row"><div class="field"><label>Percentage</label><input id="pa" class="input" type="number" value="20"></div><div class="field"><label>Of</label><input id="pb" class="input" type="number" value="100"></div></div>`,()=>((Number($("#pa").value)/100)*Number($("#pb").value)).toLocaleString())}
function discountTool(){simpleCalc("Discount",`<div class="row"><div class="field"><label>Original price</label><input id="price" class="input" type="number" value="100"></div><div class="field"><label>Discount %</label><input id="disc" class="input" type="number" value="20"></div></div>`,()=>{const p=Number($("#price").value),d=Number($("#disc").value);return`Save ${ (p*d/100).toFixed(2) } · Pay ${ (p*(1-d/100)).toFixed(2) }`})}
function tipTool(){simpleCalc("Tip",`<div class="three"><div class="field"><label>Bill</label><input id="bill" class="input" type="number" value="100"></div><div class="field"><label>Tip %</label><input id="tip" class="input" type="number" value="15"></div><div class="field"><label>People</label><input id="people" class="input" type="number" value="2" min="1"></div></div>`,()=>{const b=Number($("#bill").value),t=Number($("#tip").value),p=Math.max(1,Number($("#people").value));return`Tip ${ (b*t/100).toFixed(2) } · Total ${ (b*(1+t/100)).toFixed(2) } · ${ (b*(1+t/100)/p).toFixed(2) } / person`})}
function ageTool(){content.innerHTML=`<div class="tool-ui"><div class="field"><label>Date of birth</label><input id="dob" class="input" type="date"></div><button class="btn" id="ageGo">Calculate age</button><div id="ageOut" class="output hidden"></div></div>`;$("#ageGo").onclick=()=>{const d=new Date($("#dob").value);if(isNaN(d))return;const n=new Date();let a=n.getFullYear()-d.getFullYear();const m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))a--;$("#ageOut").classList.remove("hidden");$("#ageOut").innerHTML=`<div class="big">${a} years</div>`}}
function averageTool(){simpleCalc("Average",`<div class="field"><label>Numbers</label><textarea id="avg" class="input" rows="6" placeholder="10, 20, 30"></textarea></div>`,()=>{const a=$("#avg").value.split(/[\s,;]+/).map(Number).filter(Number.isFinite);return a.length?(a.reduce((x,y)=>x+y,0)/a.length).toLocaleString(undefined,{maximumFractionDigits:8}):"Enter numbers"})}

const maps={
length:{meter:1,kilometer:1000,centimeter:.01,millimeter:.001,mile:1609.344,foot:.3048,inch:.0254},
weight:{kilogram:1,gram:.001,milligram:.000001,pound:.45359237,ounce:.0283495},
temperature:{C:1,F:2,K:3},data:{byte:1,KB:1024,MB:1024**2,GB:1024**3,TB:1024**4},
time:{second:1,minute:60,hour:3600,day:86400}
};
function converterTool(kind){const names=Object.keys(maps[kind]);content.innerHTML=`<div class="tool-ui"><div class="row"><div class="field"><label>Value</label><input id="cv" class="input" type="number" value="1"></div><div class="field"><label>From</label><select id="cf" class="input">${names.map(x=>`<option>${x}</option>`).join("")}</select></div></div><div class="field"><label>To</label><select id="ct" class="input">${names.map(x=>`<option>${x}</option>`).join("")}</select></div><button class="btn" id="convertGo">Convert</button><div id="convertOut" class="output hidden"></div></div>`;$("#convertGo").onclick=()=>{let v=Number($("#cv").value),f=$("#cf").value,t=$("#ct").value;let out;if(kind==="temperature"){const c=f==="C"?v:f==="F"?(v-32)*5/9:v-273.15;out=t==="C"?c:t==="F"?c*9/5+32:c+273.15}else out=v*maps[kind][f]/maps[kind][t];$("#convertOut").classList.remove("hidden");$("#convertOut").innerHTML=`<div class="big">${out.toLocaleString(undefined,{maximumFractionDigits:10})} ${t}</div>`}}
function passwordTool(){content.innerHTML=`<div class="tool-ui"><div class="field"><label>Length: <span id="plv">18</span></label><input id="pl" class="range" type="range" min="6" max="64" value="18"></div><label class="check"><input id="upper" type="checkbox" checked> Uppercase</label><label class="check"><input id="num" type="checkbox" checked> Numbers</label><label class="check"><input id="sym" type="checkbox" checked> Symbols</label><div class="copy-row"><input id="pass" class="input" readonly><button class="btn secondary" id="copyPass">Copy</button></div><button class="btn" id="genPass">Generate password</button></div>`;const gen=()=>{let s="abcdefghijklmnopqrstuvwxyz";if($("#upper").checked)s+="ABCDEFGHIJKLMNOPQRSTUVWXYZ";if($("#num").checked)s+="0123456789";if($("#sym").checked)s+="!@#$%^&*()-_=+";const a=new Uint32Array(64);crypto.getRandomValues(a);let o="";for(let i=0;i<+$("#pl").value;i++)o+=s[a[i]%s.length];$("#pass").value=o};$("#pl").oninput=e=>{$("#plv").textContent=e.target.value;gen()};$("#genPass").onclick=gen;$("#copyPass").onclick=()=>navigator.clipboard?.writeText($("#pass").value);gen()}
function uuidTool(){content.innerHTML=`<div class="tool-ui"><div class="copy-row"><input id="uuidOut" class="input" readonly><button class="btn secondary" id="copyUuid">Copy</button></div><button class="btn" id="genUuid">Generate UUID</button></div>`;const gen=()=>$("#uuidOut").value=crypto.randomUUID?crypto.randomUUID():"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3)|8;return v.toString(16)});$("#genUuid").onclick=gen;$("#copyUuid").onclick=()=>navigator.clipboard?.writeText($("#uuidOut").value);gen()}
function randomTool(){simpleCalc("Random number",`<div class="row"><div class="field"><label>Minimum</label><input id="rmin" class="input" type="number" value="1"></div><div class="field"><label>Maximum</label><input id="rmax" class="input" type="number" value="100"></div></div>`,()=>{let a=Number($("#rmin").value),b=Number($("#rmax").value);if(a>b)[a,b]=[b,a];return String(Math.floor(Math.random()*(b-a+1))+a)})}
function loremTool(){content.innerHTML=`<div class="tool-ui"><div class="field"><label>Paragraphs</label><input id="lp" class="input" type="number" value="2" min="1" max="10"></div><button class="btn" id="lgo">Generate</button><textarea id="lout" class="input" rows="12"></textarea></div>`;const p="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere, erat at interdum consequat, justo augue facilisis nibh, vitae volutpat arcu sem sed lectus.";$("#lgo").onclick=()=>$("#lout").value=Array.from({length:Math.min(10,Math.max(1,Number($("#lp").value)||1))},()=>p).join("\n\n")}

function base64Tool(){content.innerHTML=`<div class="tool-ui"><textarea id="bIn" class="input" rows="8" placeholder="Text"></textarea><div class="actions"><button class="btn" id="bEnc">Encode</button><button class="btn secondary" id="bDec">Decode</button></div><textarea id="bOut" class="input" rows="8" readonly></textarea></div>`;$("#bEnc").onclick=()=>$("#bOut").value=btoa(unescape(encodeURIComponent($("#bIn").value)));$("#bDec").onclick=()=>{try{$("#bOut").value=decodeURIComponent(escape(atob($("#bIn").value)))}catch{alert("Invalid Base64 text.")}}}
function urlTool(){content.innerHTML=`<div class="tool-ui"><textarea id="uIn" class="input" rows="7" placeholder="Text or URL"></textarea><div class="actions"><button class="btn" id="uEnc">Encode</button><button class="btn secondary" id="uDec">Decode</button></div><textarea id="uOut" class="input" rows="7" readonly></textarea></div>`;$("#uEnc").onclick=()=>$("#uOut").value=encodeURIComponent($("#uIn").value);$("#uDec").onclick=()=>{try{$("#uOut").value=decodeURIComponent($("#uIn").value)}catch{alert("Invalid encoded text.")}}}
function jsonTool(){content.innerHTML=`<div class="tool-ui"><textarea id="jIn" class="input" rows="12" placeholder='{"hello":"world"}'></textarea><div class="actions"><button class="btn" id="jFmt">Format</button><button class="btn secondary" id="jMin">Minify</button></div><textarea id="jOut" class="input" rows="12" readonly></textarea></div>`;const run=min=>{try{$("#jOut").value=JSON.stringify(JSON.parse($("#jIn").value),null,min?0:2)}catch{$("#jOut").value="Invalid JSON"}};$("#jFmt").onclick=()=>run(false);$("#jMin").onclick=()=>run(true)}
async function shaTool(){content.innerHTML=`<div class="tool-ui"><textarea id="shaIn" class="input" rows="8" placeholder="Text to hash"></textarea><button class="btn" id="shaGo">Create SHA-256</button><div class="output"><div id="shaOut" class="big" style="word-break:break-all;font-size:18px">—</div></div></div>`;$("#shaGo").onclick=async()=>{const data=new TextEncoder().encode($("#shaIn").value),hash=await crypto.subtle.digest("SHA-256",data);$("#shaOut").textContent=[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join("")}}

function timestampTool(){content.innerHTML=`<div class="tool-ui"><div class="row"><div class="field"><label>Date & time</label><input id="dateIn" class="input" type="datetime-local"></div><div class="field"><label>Unix timestamp</label><input id="tsIn" class="input" type="number" placeholder="e.g. 1760000000"></div></div><div class="actions"><button class="btn" id="dateToTs">Date → timestamp</button><button class="btn secondary" id="tsToDate">Timestamp → date</button></div><div id="tsOut" class="output"></div></div>`;const now=new Date();$("#dateIn").value=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,16);$("#dateToTs").onclick=()=>{$("#tsOut").innerHTML=`<div class="big">${Math.floor(new Date($("#dateIn").value).getTime()/1000)}</div>`};$("#tsToDate").onclick=()=>{$("#tsOut").innerHTML=`<div class="big">${new Date(Number($("#tsIn").value)*1000).toLocaleString()}</div>`}}
function countdownTool(){content.innerHTML=`<div class="tool-ui"><div class="row"><div class="field"><label>Minutes</label><input id="mins" class="input" type="number" value="5" min="0"></div><div class="field"><label>Seconds</label><input id="secs" class="input" type="number" value="0" min="0" max="59"></div></div><button class="btn" id="startCd">Start countdown</button><button class="btn secondary" id="stopCd">Stop</button><div class="output"><div id="cdOut" class="big">05:00</div></div></div>`;let timer=null,total=300;const paint=()=>$("#cdOut").textContent=`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`;$("#startCd").onclick=()=>{clearInterval(timer);total=Math.max(0,Number($("#mins").value||0)*60+Number($("#secs").value||0));paint();timer=setInterval(()=>{total--;paint();if(total<=0){clearInterval(timer);alert("Countdown finished.");}},1000)};$("#stopCd").onclick=()=>clearInterval(timer)}

const toolFns={...imageFns,crop:cropTool,rotate:rotateTool,words:wordTool,case:caseTool,dedupe:dedupeTool,slug:slugTool,sortlines:sortTool,percent:percentTool,discount:discountTool,tip:tipTool,age:ageTool,average:averageTool,length:()=>converterTool("length"),weight:()=>converterTool("weight"),temperature:()=>converterTool("temperature"),data:()=>converterTool("data"),timezones:()=>converterTool("time"),password:passwordTool,uuid:uuidTool,random:randomTool,lorem:loremTool,base64:base64Tool,url:urlTool,json:jsonTool,sha:shaTool,timestamp:timestampTool,countdown:countdownTool};

function addGuide(t){const g={compress:["What it does","Compression reduces file size, which can make images easier to upload, store and share."],resize:["What it does","Resizing changes pixel dimensions. Keeping the aspect ratio can help prevent distortion."],convert:["What it does","Conversion changes the file format so the image fits another workflow or service."],words:["What it does","The counter measures words, characters and lines and estimates reading time."],password:["What it does","The generator creates a random password locally. Use unique passwords for important accounts."],json:["What it does","The formatter parses JSON, then outputs readable or minified JSON."],sha:["What it does","SHA-256 produces a fixed-length cryptographic hash for the text you enter."]}[t];if(!g)return;const el=document.createElement("div");el.className="tool-guide";el.innerHTML=`<h3>${g[0]}</h3><p>${g[1]}</p>`;content.appendChild(el)}

window.addEventListener("hashchange",()=>{if(location.hash==="#workspace"&&state.tool)workspace.classList.remove("hidden")});
